name: Release RPM

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    name: Upload RPMs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: ${{ github.event.inputs.release }}
          draft: false
          prerelease: false

      - name: Build RPM packages
        id: rpm_build
        env:
          _TAG_ : 'refs/tags/${{ github.event.inputs.tag }}'
          _RELEASE_: "1"
          _COMMITTER_: "gh-actions"
          _CHANGELOG_: "new release"
          _ARCH_: "x86_64"
        run: |
          export _VERSION_=$(echo $_TAG_ | sed 's/[^0-9|.]*//g')
          make containerized_build_rpm
          make containerized_build_container_rpm
          cd _output/rpmbuild/
          sudo tar czvf /tmp/kepler.rpm.tar.gz RPMS/
          
      - name: release rpm
        uses: softprops/action-gh-release@master
        if: startsWith(github.ref, 'refs/heads')
        with:
            files: |
              /tmp/kepler.rpm.tar.gz
  
  create-release-branch:
    name: Create release branch
    needs: [build]
    runs-on: ubuntu-latest
    steps: 
    - name: Create release branch
      uses: peterjgrainger/action-create-branch@v2.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: ${{ github.event.inputs.release }}
        sha: '${{ github.event.pull_request.head.sha }}'
      
  
  push-image:
    name: Push image to the registry
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Quay
      uses: docker/login-action@v1
      with:
        registry: quay.io/sustainable_computing_io
        username: ${{ secrets.BOT_NAME }}
        password: ${{ secrets.BOT_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
          context: .
          platforms: linux/amd64
          push: true
          tags: quay.io/sustainable_computing_io/kepler
          labels: latest, ${{ github.event.inputs.release }}
          file: build/Dockerfile
